version: 0.0
os: linux 
files: 
  - source : / 
    destination: /var/www/html/
file_exists_behavior: OVERWRITE 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall: 
    - location: scripts/artisan.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/server_restart.sh
      timeout: 300
      runas: root
